name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      artifact_suffix: ${{ github.ref_type == 'branch' && format('{0}_{1}', github.ref_name, github.sha )|| github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          pwd
          mkdir zips
          projects=$( find ./ -name "package.json" )
          for prj_file in ${projects} ; do
            prj_dir=$( dirname $prj_file )
            prj_name=$( cat ${prj_file} | jq -r '.name' )
            echo "NODE LAMBDA IN ${prj_dir}"
            (cd ${prj_dir} && npm run --if-present build-archive )
            lambda_archive_name="${prj_dir}/${prj_name}.zip"
            libraries_archive_name="${prj_dir}/${prj_name}-liblayer.zip"
            if ( [ -e "${lambda_archive_name}" ] ) then
              mv "${lambda_archive_name}" zips
            fi
            if ( [ -e "${libraries_archive_name}" ] ) then
              mv "${libraries_archive_name}" zips
            fi
          done
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all_lambdas__${{ env.artifact_suffix }}
          path: zips/*.zip
