on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Repository tag to use'
        required: true
        type: string

name: Create Release
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: List build action execution
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh --json -R ${{ github.repository }} run list -w Build 
              
