on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Repository tag to use'
        required: true
        type: string

name: Create Release
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: List build action execution
        run: |
          gh -R marcovit79/github_actions_first_exercise run list -w build
